const experienceData = [
    {
        company: 'ООО "Рога и Копыта"',
        position: "Junior Frontend-разработчик",
        period: {
            start: 2020,
            end: 2022,
        },
    },
    {
        company: "Яндекс",
        position: "Middle Frontend-разработчик",
        period: {
            start: 2022,
            end: 2025,
        },
    },
    {
        company: "Сумасшедший дом",
        position: "Пациент",
        period: {
            start: 2025,
        },
    },
];

const skillsData = [
    {
        category: "Фронтенд",
        items: ["HTML", "CSS", "JavaScript"],
    },
    {
        category: "Инструменты",
        items: ["Git"],
    },
    {
        category: "Языки",
        items: [
            {
                name: "Русский",
                level: "Носитель",
            },
            {
                name: "English",
                level: "Intermediate",
            },
        ],
    },
];

const REPOS = [
    {
        id: 1073213774,
        node_id: "R_kgDOP_fxTg",
        name: "js-assignments",
        full_name: "sonantedd/js-assignments",
        private: false,
        owner: {
            login: "sonantedd",
            id: 88681029,
            node_id: "MDQ6VXNlcjg4NjgxMDI5",
            avatar_url: "https://avatars.githubusercontent.com/u/88681029?v=4",
            gravatar_id: "",
            url: "https://api.github.com/users/sonantedd",
            html_url: "https://github.com/sonantedd",
            followers_url: "https://api.github.com/users/sonantedd/followers",
            following_url: "https://api.github.com/users/sonantedd/following{/other_user}",
            gists_url: "https://api.github.com/users/sonantedd/gists{/gist_id}",
            starred_url: "https://api.github.com/users/sonantedd/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/sonantedd/subscriptions",
            organizations_url: "https://api.github.com/users/sonantedd/orgs",
            repos_url: "https://api.github.com/users/sonantedd/repos",
            events_url: "https://api.github.com/users/sonantedd/events{/privacy}",
            received_events_url: "https://api.github.com/users/sonantedd/received_events",
            type: "User",
            user_view_type: "public",
            site_admin: false,
        },
        html_url: "https://github.com/sonantedd/js-assignments",
        description: null,
        fork: false,
        url: "https://api.github.com/repos/sonantedd/js-assignments",
        forks_url: "https://api.github.com/repos/sonantedd/js-assignments/forks",
        keys_url: "https://api.github.com/repos/sonantedd/js-assignments/keys{/key_id}",
        collaborators_url:
            "https://api.github.com/repos/sonantedd/js-assignments/collaborators{/collaborator}",
        teams_url: "https://api.github.com/repos/sonantedd/js-assignments/teams",
        hooks_url: "https://api.github.com/repos/sonantedd/js-assignments/hooks",
        issue_events_url:
            "https://api.github.com/repos/sonantedd/js-assignments/issues/events{/number}",
        events_url: "https://api.github.com/repos/sonantedd/js-assignments/events",
        assignees_url: "https://api.github.com/repos/sonantedd/js-assignments/assignees{/user}",
        branches_url: "https://api.github.com/repos/sonantedd/js-assignments/branches{/branch}",
        tags_url: "https://api.github.com/repos/sonantedd/js-assignments/tags",
        blobs_url: "https://api.github.com/repos/sonantedd/js-assignments/git/blobs{/sha}",
        git_tags_url: "https://api.github.com/repos/sonantedd/js-assignments/git/tags{/sha}",
        git_refs_url: "https://api.github.com/repos/sonantedd/js-assignments/git/refs{/sha}",
        trees_url: "https://api.github.com/repos/sonantedd/js-assignments/git/trees{/sha}",
        statuses_url: "https://api.github.com/repos/sonantedd/js-assignments/statuses/{sha}",
        languages_url: "https://api.github.com/repos/sonantedd/js-assignments/languages",
        stargazers_url: "https://api.github.com/repos/sonantedd/js-assignments/stargazers",
        contributors_url: "https://api.github.com/repos/sonantedd/js-assignments/contributors",
        subscribers_url: "https://api.github.com/repos/sonantedd/js-assignments/subscribers",
        subscription_url: "https://api.github.com/repos/sonantedd/js-assignments/subscription",
        commits_url: "https://api.github.com/repos/sonantedd/js-assignments/commits{/sha}",
        git_commits_url: "https://api.github.com/repos/sonantedd/js-assignments/git/commits{/sha}",
        comments_url: "https://api.github.com/repos/sonantedd/js-assignments/comments{/number}",
        issue_comment_url:
            "https://api.github.com/repos/sonantedd/js-assignments/issues/comments{/number}",
        contents_url: "https://api.github.com/repos/sonantedd/js-assignments/contents/{+path}",
        compare_url:
            "https://api.github.com/repos/sonantedd/js-assignments/compare/{base}...{head}",
        merges_url: "https://api.github.com/repos/sonantedd/js-assignments/merges",
        archive_url: "https://api.github.com/repos/sonantedd/js-assignments/{archive_format}{/ref}",
        downloads_url: "https://api.github.com/repos/sonantedd/js-assignments/downloads",
        issues_url: "https://api.github.com/repos/sonantedd/js-assignments/issues{/number}",
        pulls_url: "https://api.github.com/repos/sonantedd/js-assignments/pulls{/number}",
        milestones_url: "https://api.github.com/repos/sonantedd/js-assignments/milestones{/number}",
        notifications_url:
            "https://api.github.com/repos/sonantedd/js-assignments/notifications{?since,all,participating}",
        labels_url: "https://api.github.com/repos/sonantedd/js-assignments/labels{/name}",
        releases_url: "https://api.github.com/repos/sonantedd/js-assignments/releases{/id}",
        deployments_url: "https://api.github.com/repos/sonantedd/js-assignments/deployments",
        created_at: "2025-10-09T19:23:58Z",
        updated_at: "2025-10-09T19:32:47Z",
        pushed_at: "2025-10-09T19:32:43Z",
        git_url: "git://github.com/sonantedd/js-assignments.git",
        ssh_url: "git@github.com:sonantedd/js-assignments.git",
        clone_url: "https://github.com/sonantedd/js-assignments.git",
        svn_url: "https://github.com/sonantedd/js-assignments",
        homepage: null,
        size: 1,
        stargazers_count: 0,
        watchers_count: 0,
        language: "JavaScript",
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        has_discussions: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [],
        visibility: "public",
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: "main",
    },
    {
        id: 1068110845,
        node_id: "R_kgDOP6oT_Q",
        name: "portfolio",
        full_name: "sonantedd/portfolio",
        private: false,
        owner: {
            login: "sonantedd",
            id: 88681029,
            node_id: "MDQ6VXNlcjg4NjgxMDI5",
            avatar_url: "https://avatars.githubusercontent.com/u/88681029?v=4",
            gravatar_id: "",
            url: "https://api.github.com/users/sonantedd",
            html_url: "https://github.com/sonantedd",
            followers_url: "https://api.github.com/users/sonantedd/followers",
            following_url: "https://api.github.com/users/sonantedd/following{/other_user}",
            gists_url: "https://api.github.com/users/sonantedd/gists{/gist_id}",
            starred_url: "https://api.github.com/users/sonantedd/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/sonantedd/subscriptions",
            organizations_url: "https://api.github.com/users/sonantedd/orgs",
            repos_url: "https://api.github.com/users/sonantedd/repos",
            events_url: "https://api.github.com/users/sonantedd/events{/privacy}",
            received_events_url: "https://api.github.com/users/sonantedd/received_events",
            type: "User",
            user_view_type: "public",
            site_admin: false,
        },
        html_url: "https://github.com/sonantedd/portfolio",
        description: null,
        fork: false,
        url: "https://api.github.com/repos/sonantedd/portfolio",
        forks_url: "https://api.github.com/repos/sonantedd/portfolio/forks",
        keys_url: "https://api.github.com/repos/sonantedd/portfolio/keys{/key_id}",
        collaborators_url:
            "https://api.github.com/repos/sonantedd/portfolio/collaborators{/collaborator}",
        teams_url: "https://api.github.com/repos/sonantedd/portfolio/teams",
        hooks_url: "https://api.github.com/repos/sonantedd/portfolio/hooks",
        issue_events_url: "https://api.github.com/repos/sonantedd/portfolio/issues/events{/number}",
        events_url: "https://api.github.com/repos/sonantedd/portfolio/events",
        assignees_url: "https://api.github.com/repos/sonantedd/portfolio/assignees{/user}",
        branches_url: "https://api.github.com/repos/sonantedd/portfolio/branches{/branch}",
        tags_url: "https://api.github.com/repos/sonantedd/portfolio/tags",
        blobs_url: "https://api.github.com/repos/sonantedd/portfolio/git/blobs{/sha}",
        git_tags_url: "https://api.github.com/repos/sonantedd/portfolio/git/tags{/sha}",
        git_refs_url: "https://api.github.com/repos/sonantedd/portfolio/git/refs{/sha}",
        trees_url: "https://api.github.com/repos/sonantedd/portfolio/git/trees{/sha}",
        statuses_url: "https://api.github.com/repos/sonantedd/portfolio/statuses/{sha}",
        languages_url: "https://api.github.com/repos/sonantedd/portfolio/languages",
        stargazers_url: "https://api.github.com/repos/sonantedd/portfolio/stargazers",
        contributors_url: "https://api.github.com/repos/sonantedd/portfolio/contributors",
        subscribers_url: "https://api.github.com/repos/sonantedd/portfolio/subscribers",
        subscription_url: "https://api.github.com/repos/sonantedd/portfolio/subscription",
        commits_url: "https://api.github.com/repos/sonantedd/portfolio/commits{/sha}",
        git_commits_url: "https://api.github.com/repos/sonantedd/portfolio/git/commits{/sha}",
        comments_url: "https://api.github.com/repos/sonantedd/portfolio/comments{/number}",
        issue_comment_url:
            "https://api.github.com/repos/sonantedd/portfolio/issues/comments{/number}",
        contents_url: "https://api.github.com/repos/sonantedd/portfolio/contents/{+path}",
        compare_url: "https://api.github.com/repos/sonantedd/portfolio/compare/{base}...{head}",
        merges_url: "https://api.github.com/repos/sonantedd/portfolio/merges",
        archive_url: "https://api.github.com/repos/sonantedd/portfolio/{archive_format}{/ref}",
        downloads_url: "https://api.github.com/repos/sonantedd/portfolio/downloads",
        issues_url: "https://api.github.com/repos/sonantedd/portfolio/issues{/number}",
        pulls_url: "https://api.github.com/repos/sonantedd/portfolio/pulls{/number}",
        milestones_url: "https://api.github.com/repos/sonantedd/portfolio/milestones{/number}",
        notifications_url:
            "https://api.github.com/repos/sonantedd/portfolio/notifications{?since,all,participating}",
        labels_url: "https://api.github.com/repos/sonantedd/portfolio/labels{/name}",
        releases_url: "https://api.github.com/repos/sonantedd/portfolio/releases{/id}",
        deployments_url: "https://api.github.com/repos/sonantedd/portfolio/deployments",
        created_at: "2025-10-01T21:47:45Z",
        updated_at: "2025-10-10T22:30:48Z",
        pushed_at: "2025-10-10T22:30:44Z",
        git_url: "git://github.com/sonantedd/portfolio.git",
        ssh_url: "git@github.com:sonantedd/portfolio.git",
        clone_url: "https://github.com/sonantedd/portfolio.git",
        svn_url: "https://github.com/sonantedd/portfolio",
        homepage: null,
        size: 294,
        stargazers_count: 0,
        watchers_count: 0,
        language: "HTML",
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        has_discussions: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [],
        visibility: "public",
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: "main",
    },
    {
        id: 1080767360,
        node_id: "R_kgDOQGszgA",
        name: "to-do-list",
        full_name: "sonantedd/to-do-list",
        private: false,
        owner: {
            login: "sonantedd",
            id: 88681029,
            node_id: "MDQ6VXNlcjg4NjgxMDI5",
            avatar_url: "https://avatars.githubusercontent.com/u/88681029?v=4",
            gravatar_id: "",
            url: "https://api.github.com/users/sonantedd",
            html_url: "https://github.com/sonantedd",
            followers_url: "https://api.github.com/users/sonantedd/followers",
            following_url: "https://api.github.com/users/sonantedd/following{/other_user}",
            gists_url: "https://api.github.com/users/sonantedd/gists{/gist_id}",
            starred_url: "https://api.github.com/users/sonantedd/starred{/owner}{/repo}",
            subscriptions_url: "https://api.github.com/users/sonantedd/subscriptions",
            organizations_url: "https://api.github.com/users/sonantedd/orgs",
            repos_url: "https://api.github.com/users/sonantedd/repos",
            events_url: "https://api.github.com/users/sonantedd/events{/privacy}",
            received_events_url: "https://api.github.com/users/sonantedd/received_events",
            type: "User",
            user_view_type: "public",
            site_admin: false,
        },
        html_url: "https://github.com/sonantedd/to-do-list",
        description: null,
        fork: false,
        url: "https://api.github.com/repos/sonantedd/to-do-list",
        forks_url: "https://api.github.com/repos/sonantedd/to-do-list/forks",
        keys_url: "https://api.github.com/repos/sonantedd/to-do-list/keys{/key_id}",
        collaborators_url:
            "https://api.github.com/repos/sonantedd/to-do-list/collaborators{/collaborator}",
        teams_url: "https://api.github.com/repos/sonantedd/to-do-list/teams",
        hooks_url: "https://api.github.com/repos/sonantedd/to-do-list/hooks",
        issue_events_url:
            "https://api.github.com/repos/sonantedd/to-do-list/issues/events{/number}",
        events_url: "https://api.github.com/repos/sonantedd/to-do-list/events",
        assignees_url: "https://api.github.com/repos/sonantedd/to-do-list/assignees{/user}",
        branches_url: "https://api.github.com/repos/sonantedd/to-do-list/branches{/branch}",
        tags_url: "https://api.github.com/repos/sonantedd/to-do-list/tags",
        blobs_url: "https://api.github.com/repos/sonantedd/to-do-list/git/blobs{/sha}",
        git_tags_url: "https://api.github.com/repos/sonantedd/to-do-list/git/tags{/sha}",
        git_refs_url: "https://api.github.com/repos/sonantedd/to-do-list/git/refs{/sha}",
        trees_url: "https://api.github.com/repos/sonantedd/to-do-list/git/trees{/sha}",
        statuses_url: "https://api.github.com/repos/sonantedd/to-do-list/statuses/{sha}",
        languages_url: "https://api.github.com/repos/sonantedd/to-do-list/languages",
        stargazers_url: "https://api.github.com/repos/sonantedd/to-do-list/stargazers",
        contributors_url: "https://api.github.com/repos/sonantedd/to-do-list/contributors",
        subscribers_url: "https://api.github.com/repos/sonantedd/to-do-list/subscribers",
        subscription_url: "https://api.github.com/repos/sonantedd/to-do-list/subscription",
        commits_url: "https://api.github.com/repos/sonantedd/to-do-list/commits{/sha}",
        git_commits_url: "https://api.github.com/repos/sonantedd/to-do-list/git/commits{/sha}",
        comments_url: "https://api.github.com/repos/sonantedd/to-do-list/comments{/number}",
        issue_comment_url:
            "https://api.github.com/repos/sonantedd/to-do-list/issues/comments{/number}",
        contents_url: "https://api.github.com/repos/sonantedd/to-do-list/contents/{+path}",
        compare_url: "https://api.github.com/repos/sonantedd/to-do-list/compare/{base}...{head}",
        merges_url: "https://api.github.com/repos/sonantedd/to-do-list/merges",
        archive_url: "https://api.github.com/repos/sonantedd/to-do-list/{archive_format}{/ref}",
        downloads_url: "https://api.github.com/repos/sonantedd/to-do-list/downloads",
        issues_url: "https://api.github.com/repos/sonantedd/to-do-list/issues{/number}",
        pulls_url: "https://api.github.com/repos/sonantedd/to-do-list/pulls{/number}",
        milestones_url: "https://api.github.com/repos/sonantedd/to-do-list/milestones{/number}",
        notifications_url:
            "https://api.github.com/repos/sonantedd/to-do-list/notifications{?since,all,participating}",
        labels_url: "https://api.github.com/repos/sonantedd/to-do-list/labels{/name}",
        releases_url: "https://api.github.com/repos/sonantedd/to-do-list/releases{/id}",
        deployments_url: "https://api.github.com/repos/sonantedd/to-do-list/deployments",
        created_at: "2025-10-21T20:52:51Z",
        updated_at: "2025-10-21T20:52:55Z",
        pushed_at: "2025-10-21T20:57:51Z",
        git_url: "git://github.com/sonantedd/to-do-list.git",
        ssh_url: "git@github.com:sonantedd/to-do-list.git",
        clone_url: "https://github.com/sonantedd/to-do-list.git",
        svn_url: "https://github.com/sonantedd/to-do-list",
        homepage: null,
        size: 266,
        stargazers_count: 0,
        watchers_count: 0,
        language: null,
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        has_discussions: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [],
        visibility: "public",
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: "main",
    },
];
